default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  password: passer 
  database: prevu_development
  host: localhost

test:
  <<: *default
  database: prevu_test

production:
  <<: *default
